apis/hole.go
models/hole.go
tests/division_test.go
tests/hole_test.go
tests/utils.go
utils/utils.go

handle default values(divisionID and empty Tags)
encapsulate repeat codes into functions
add admin associated querySet constructor
merge sql operations when find or create Tags of A hole

fix(hole): better sql and code style

---

apis/hole/schemas.go
go.mod

fix: validation

---

apis/floor/apis.go
apis/floor/routes.go
apis/floor/schemas.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
models/floor.go

Feat restore history

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
models/base.go
models/division.go
models/floor.go
models/hole.go
models/report.go
models/tag.go

floors -> prefetch 
id -> division_id, hole_id, floor_id, tag_id, report_id

fix: json name

---

models/hole.go

fix: loadFloor right undefined

---

models/floor.go

fix: null to []

---

models/floor.go

update hole updated_at
fix sql error and logic err when set floor storey

Fix create floor

---

apis/hole/apis.go
apis/hole/schemas.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
models/hole.go

add unhidden field
fix: hole cache when modify and delete hole
fix: set tag.tagID

Feat unhidden

---

models/hole.go

feat: [temp] no ordering hole by created_time

---

apis/favourite/api.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml

feat: favorite plain use Map{"data":data} to response

---

apis/floor/apis.go
tests/floor_test.go

fix: modifyFloor logic

---

bootstrap/init.go

feat-fiber.log

---

apis/floor/apis.go
apis/floor/routes.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml

Get Punishment History

---

apis/hole/apis.go
apis/hole/schemas.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml

The ListHolesByDivision function does not provide an option to sort by create time or reply time. This pull request is adding this option.

Add List by Order Option to ListHolesByDivision

---

apis/floor/apis.go
apis/hole/apis.go

Checking permission when creating hole or floor with special tags

fix: check special tag permission

---

apis/penalty/api.go
apis/penalty/schemas.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
models/punishment.go

解封接口，根据楼层或用户ID解封，解封时间由请求提供。
创建同一楼层的解封记录会产生相同的floorID，将floor_id由唯一索引改成普通索引

feat: unban user by user ID or floor ID

---

apis/floor/apis.go
apis/floor/search.go
models/elastic.go
models/floor.go
models/hole.go

Prefetch Hole Floors without sensitive

Load Floors Without Sensitive Mention

---

utils/sensitive/utils.go

如果URL中不包含Scheme或Host，则将其识别为表情包。

修复：表情包被识别为外链

---

bootstrap/init.go
config/config.go
utils/sensitive/api.go

do not merge until ensure yidun/service/antispam/label can access internet

SensitiveLabelMap

---

apis/hole/apis.go
apis/report/apis.go
apis/tag/apis.go
models/admin_log.go

feat: add admin log for hide hole, modify tag, delete report

---

README.md
apis/division/apis.go
apis/floor/apis.go
apis/floor/search.go
apis/hole/apis.go
apis/message/apis.go
apis/penalty/api.go
apis/report/apis.go
apis/routes.go
apis/tag/apis.go
apis/user/apis.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
models/elastic.go
models/floor.go
models/hole.go
models/user.go

resolve #176 
floor 搜索接口，新增参数（开始时间和截止时间），用于按照时间范围筛选搜索的楼层。
目前的 es query
```
{
"query": {
"bool": {
"must": {
"dis_max": {
"queries": [
{
"multi_match": {}
},
{
"multi_match": {}
}
]
}
},
"filter": {
//Term filter
}
}
}
}
```

feat: support filtering by time range in floor searching

---

apis/hole/apis.go
apis/hole/routes.go
apis/hole/schemas.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml

- Add `CreatedStart`, `CreatedEnd`, and `Tags` to ListOldModel
- Update `ListHolesOld` to filter by creation time range and multiple tags 
- resolve #179

feat(api/holes): support filtering by creation time and multiple tags
